dbus: remove API key in Query method
Avoid using API key in DBus Query method.

You can try it with gdbus:
$ gdbus call --session --dest org.mfs.Gtrakt.FeedServer
--object-path /org/mfs/Gtrakt/FeedServer --method
org.mfs.Gtrakt.FeedServer.Query "batman" 1

It shoud return something like:
Error: Se alcanzó el tiempo de expiración
(According to introspection data, you need to pass `si')

Signed-off-by: Jorge Munhoz Castanher <punkto@gmail.com>